Error on: C:\Users\Αλεχ\Desktop\Server\build v.1\build\dist\gameserver\data\scripts\quests\93_SagaOfTheSpectralMaster\__init__.py.error.LOGGER
Line: -1 - Column: -1

Traceback (innermost last):
  File "__init__.py", line 5, in ?
ImportError: no module named quests
